site_name: esmBot
docs_dir: docs/
repo_name: 'esmBot/esmBot'
repo_url: 'https://github.com/esmBot/esmBot'
copyright: Copyright &copy; 2018 - 2024 <a href="https://essem.space">Essem</a>
nav:
    - Home: index.md
    - setup.md
    - config.md
    - custom-commands.md
    - bun.md
    - containers.md
    - postgresql.md
markdown_extensions:
  - def_list
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
theme:
  name: 'material'
  features:
    - toc.integrate
    - content.tabs.link
  logo: assets/esmbot.png
  favicon: assets/esmbot.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
plugins:
  - glightbox
  - git-revision-date-localized
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://wetdry.world/@esmBot
    - icon: fontawesome/brands/github
      link: https://github.com/esmBot
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/TheEssem